[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
peach_v1 = "EYz3GPbE1qoXS3i4ziRmfyTQgVjZt3ymMxYKZZiEaEED"

[programs.localnet]
peach_v1 = "EYz3GPbE1qoXS3i4ziRmfyTQgVjZt3ymMxYKZZiEaEED"

[programs.mainnet]
peach_v1 = "DsLASEbqzgRGjyFJJQbjK1SWnmjjpCrjfkGNcoP3tc5t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet" 
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/peach-v1.ts"
