[package]
name = "peach-v1"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "peach_v1"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
bytemuck = { version = "^1.7.2", features = ["min_const_generics"] }
derivative = "2.2.0"
fixed = { git = "https://github.com/blockworks-foundation/fixed.git", branch = "v1.11.0-borsh0_10-mango", features = [
    "serde",
    "borsh",
    "debug-assert-in-release",
] }
static_assertions = "1.1"
arrayref = "0.3.6"

[dev-dependencies]
num = "0.4.0"
rand = "0.8.4"
