[package]
name = "peach-v1"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "peach_v1"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
solana-sdk = []
client = []
anchor-debug = []
custom-heap = []
custom-panic = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"
bytemuck = { version = "^1.7.2", features = ["min_const_generics"] }
derivative = "2.2.0"
fixed = { git = "https://github.com/blockworks-foundation/fixed.git", branch = "v1.11.0-borsh0_10-mango", features = [
    "serde",
    "borsh",
    "debug-assert-in-release",
] }
static_assertions = "1.1"
arrayref = "0.3.6"
pyth-sdk-solana = "0.10.0"
pyth-solana-receiver-sdk = "0.3.0"
proc-macro2 = "=1.0.95"

[dev-dependencies]
num = "0.4.0"